### ISSUE TITLE
ModuleNotFoundError: No module named 'akwam'

### ISSUE THREAD

**Issue by xVoldx** [elmoiv/akwam-dl#1]
![image](https://user-images.githubusercontent.com/62064902/126895223-d5f1bd18-02b5-4f6b-bde1-c7a118bc4dde.png)

**Comment by elmoiv** [comment]
Will be publishing source soon.

**Comment by elmoiv** [comment]
Source Code has been uploaded. You can now run akwam-dl.py without any issues.

**Comment by xVoldx** [comment]
Thanks <3
