### ISSUE TITLE
it's a loop

### ISSUE THREAD

**Issue by DarshZero** [elmoiv/akwam-dl#3]
Unfortunately, I tried many links, but I get the same error.

![image](https://github.com/elmoiv/akwam-dl/assets/31729048/b6af0c3d-2ccd-46e2-b143-a1832d8bccbb)

**Comment by DarshZero** [comment]
and That's The Live Demo 

![image](https://github.com/elmoiv/akwam-dl/assets/31729048/1423fdd7-7090-4c29-a7f0-328ff0e9f941)

**Comment by elmoiv** [comment]
Unfortunately, Akwam used reCaptcha in their last update to their website.

**Comment by tarekdev7** [comment]
Is there any workaround for the Captcha ? If not, would you please make the script work for other websites. 
for example Arabseed.

**Comment by DarshZero** [comment]
Arabseed is an unregulated website and they change the domain every day. I do not prefer this idea.

**Comment by elmoiv** [comment]
I worked previously on EgyBest downloader and it was a success untill it was taken down forever.

Second choice was Akwam as it was the second best provider after EgyBest and now they are fighting scrapers and automation tools with Captchas.

The solution now is to write a script for old akwam website but it's not updated and does not have new series and movies.

:/

**Comment by elmoiv** [comment]
> Arabseed is an unregulated website and they change the domain every day. I do not prefer this idea.
> 
> ![image](https://user-images.githubusercontent.com/31729048/275321766-9cd11b77-3a73-48c7-ac60-cebe9d426fbb.png)

Changing domain is not a problem tho. Akwam was changing domains but this can be overcomed by sniffing redirections from original domain.

**Comment by elmoiv** [comment]
Fixed
