### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by AhmedMondo** [elmoiv/akwam-dl#5]
in some movies/series i get error "Error Caught -> list index out of range"
![image](https://github.com/elmoiv/akwam-dl/assets/55901601/67f64adf-9776-43d8-bac5-9a3e22cca72d)

series i searched : Loki season 1 episode 1

and in some movies it stuck on Getting Direct URL and ends up with same error 
"Error Caught -> list index out of range"
![image](https://github.com/elmoiv/akwam-dl/assets/55901601/d514023f-36d5-4d00-b100-c5648092c0d5)
Movie: Interstellar
Quality: 1080p

**Comment by elmoiv** [comment]
Yes it's due too akwam have some of its urls expired. When they fix it the problem will be gone

**Comment by AhmedMondo** [comment]
![image](https://github.com/elmoiv/akwam-dl/assets/55901601/9635b670-720c-4474-bd0c-96647bb5c8cb)


but i rewritten it and it works with me :) (in js)

**Comment by elmoiv** [comment]
Good for you! I am not working actively on this repo so feel free to fork and improve

**Comment by elmoiv** [comment]
> in some movies/series i get error "Error Caught -> list index out of range" ![image](https://private-user-images.githubusercontent.com/55901601/324292573-67f64adf-9776-43d8-bac5-9a3e22cca72d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg2MjEsIm5iZiI6MTcxMzk4ODMyMSwicGF0aCI6Ii81NTkwMTYwMS8zMjQyOTI1NzMtNjdmNjRhZGYtOTc3Ni00M2Q4LWJhYzUtOWEzZTIyY2NhNzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDljMjY4OGZlYmE2ODlmNGYzNDY0ZDQ5Y2IxMDIzNzA4MzNmZGQ5MjU3NmZmZjk1MDM3ODg5NDg2ZWI2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Fbf6pMdcalKnGuhEHoUGCVNMCOZHPOMk4_mCRAm3vE)
> 
> series i searched : Loki season 1 episode 1
> 
> and in some movies it stuck on Getting Direct URL and ends up with same error "Error Caught -> list index out of range" ![image](https://private-user-images.githubusercontent.com/55901601/324292624-d514023f-36d5-4d00-b100-c5648092c0d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg2MjEsIm5iZiI6MTcxMzk4ODMyMSwicGF0aCI6Ii81NTkwMTYwMS8zMjQyOTI2MjQtZDUxNDAyM2YtMzZkNS00ZDAwLWIxMDAtYzU2NDgwOTJjMGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NzM4ODYxY2FhZmNlZGZiOTQwN2E5MGJiNGM0MmUwNmU1MjgwMTRiOTAxMzBhNjkwYThhNWEzNGIzMmY5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7LnaTy8_JN6_cMKwXfXpRoTdxX0vl-zQhcxQm_V1YM) Movie: Interstellar Quality: 1080p

I tried it on my side now and it works correctly :/

![image](https://github.com/elmoiv/akwam-dl/assets/31712173/c0d38c7b-5ad9-45ff-84ba-7bd885dd5fe0)
