### ISSUE TITLE
Server error while downloading 

### ISSUE THREAD

**Issue by Najeeb-Patoana** [elmoiv/akwam-dl#6]
![image](https://github.com/user-attachments/assets/9ede56f1-941e-4bbd-9ae6-1c628276f33d)

This erros comes all time

**Comment by elmoiv** [comment]
Working okay on my side:
![image](https://github.com/user-attachments/assets/b148889c-eff8-42e0-b27a-bbb49da19de5)

You may need to check your network settings or ISP may be blocking this website

**Comment by Najeeb-Patoana** [comment]
**Thanks**
